
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDIDO MAS MENOS NUMERO POR\n    operacion : NUMERO MAS NUMERO\n              | NUMERO MENOS NUMERO\n              | NUMERO POR NUMERO\n              | NUMERO DIVIDIDO NUMERO\n    '
    
_lr_action_items = {'NUMERO':([0,3,4,5,6,],[2,7,8,9,10,]),'$end':([1,7,8,9,10,],[0,-1,-2,-3,-4,]),'MAS':([2,],[3,]),'MENOS':([2,],[4,]),'POR':([2,],[5,]),'DIVIDIDO':([2,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'operacion':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> operacion","S'",1,None,None,None),
  ('operacion -> NUMERO MAS NUMERO','operacion',3,'p_operacion','prueba.py',22),
  ('operacion -> NUMERO MENOS NUMERO','operacion',3,'p_operacion','prueba.py',23),
  ('operacion -> NUMERO POR NUMERO','operacion',3,'p_operacion','prueba.py',24),
  ('operacion -> NUMERO DIVIDIDO NUMERO','operacion',3,'p_operacion','prueba.py',25),
]
